### ISSUE TITLE
请问，{qproperty !} 这些关键字能加入智能感知吗？

### ISSUE THREAD

**Issue by RC1844** [PyQt5/QSSEditorVsCode#1]
RT

![image](https://user-images.githubusercontent.com/14369275/196927568-6effc7d8-e327-4323-bbe5-081917272636.png)

**Comment by 892768447** [comment]
可以的。可能我当时忘记了

**Comment by RC1844** [comment]
好耶，坐等更新

**Comment by RC1844** [comment]
@892768447 我看见你关于qproperty 的提交了，但vscode并没有实装。另外，希望控件伪状态前的"!"，也处理一下🙏

**Comment by 892768447** [comment]
> @892768447 我看见你关于qproperty 的提交了，但vscode并没有实装。另外，希望控件伪状态前的"!"，也处理一下🙏

莫慌。提示还在做。还没提交vscode插件市场。

**Comment by RC1844** [comment]
> 莫慌。提示还在做。还没提交vscode插件市场。

好嘞，期待你的更新

**Comment by 892768447** [comment]
新版本已发布

**Comment by RC1844** [comment]
> 新版本已发布

好耶,谢谢大佬

**Comment by RC1844** [comment]
不知道为什么，我更新了，但是没生效，还是之前的样子

**Comment by 892768447** [comment]
你看下版本是不是0.0.2
重启下vscode呢

**Comment by RC1844** [comment]
是0.2，重启了，缓存都删除了

**Comment by 892768447** [comment]
晚点我换个电脑测试下
按理说输入qproperty 会自动提示的

**Comment by RC1844** [comment]
我还没有进行输入测试，只是看了问题检测。晚点我再输入测试一下

**Comment by 892768447** [comment]
这个插件只是方便输入。智能提示。不做语法检测。语法检测应该是利用现成CSS的检测。

**Comment by RC1844** [comment]
好吧🤐，是我理解错了，输入没问题
