### ISSUE TITLE
Incompatibility with VSC 1.16.1

### ISSUE THREAD

**Issue by freddykat** [PyQt5/QSSEditorVsCode#2]
Hello fellow programmers,

Im designing a GUI for a MIXXX skin that mimics the OEM Pioneer CDJ2000NSX2 style.

![teste](https://user-images.githubusercontent.com/36639282/220112742-5b342067-3728-4186-917a-f42aa74f5862.jpg)

However im trying to create new widgets on VSC and preview themm however i cant find why it does not support the install of QssEditor.

I attach the picture of install error

![erro_qss](https://user-images.githubusercontent.com/36639282/220105858-638c019d-31f0-4c6a-9abb-02bee9739a68.png)

**Comment by 892768447** [comment]
https://github.com/PyQt5/QSSEditorVsCode/blob/main/package.json#L12

vscode": "^1.67.0"

you can update your vscode to lasted version 

https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-user
